language: perl
before_install:
    - sudo apt-add-repository -y ppa:rsrchboy/ndn-perl
    - sudo apt-get update -q
install:
    - sudo apt-get install -y -q build-essential debhelper devscripts equivs
    - sudo mk-build-deps --install debian/control
script:
    - debuild -S -us -uc --lintian-opts --profile ndn
    - debuild -us -uc --lintian-opts --profile ndn
    - sudo dpkg -i ../*.deb
