language: perl
env:
    global:
        - DEB_BUILD_OPTIONS="parallel=2"
    matrix:
        - PPA_REPO=ppa:rsrchboy/ndn-perl         DEPLOY=false   BUILD=source
        - PPA_REPO=ppa:rsrchboy/ndn-perl         DEPLOY=false   BUILD=binary
        - PPA_REPO=ppa:rsrchboy/ndn-perl-testing DEPLOY=testing BUILD=source
        - PPA_REPO=ppa:rsrchboy/ndn-perl-testing DEPLOY=testing BUILD=binary
matrix:
    fast_finish: true
    allow_failures:
        - env: PPA_REPO=ppa:rsrchboy/ndn-perl         DEPLOY=false   BUILD=binary
        - env: PPA_REPO=ppa:rsrchboy/ndn-perl-testing DEPLOY=testing BUILD=binary
before_install:
    - sudo apt-add-repository -y $PPA_REPO
    - sudo apt-get update -qq
install:
    - sudo apt-get install -y -q build-essential debhelper devscripts equivs
    - sudo mk-build-deps --install debian/control
script:
    - if [ "$BUILD" = "source" ] ; then debuild -S -us -uc --lintian-opts --profile ndn ; fi
    - if [ "$BUILD" = "binary" ] ; then debuild -us -uc --lintian-opts --profile ndn || { cat ~/.cpanm/build.log ; false ; } ; fi
    - if [ "$BUILD" = "binary" ] ; then  sudo dpkg -i ../*.deb ; fi
after_success:
    - openssl aes-256-cbc -K $encrypted_a72206316df8_key -iv $encrypted_a72206316df8_iv
      -in debian/travis/deploy_id.enc -out debian/travis/deploy_id -d
    - chmod 0600 debian/travis/deploy_id
    - ./debian/travis.after_success
