perl: 5.14
before_install:
    - sudo apt-add-repository -y ppa:rsrchboy/ndn-perl
    - sudo apt-get update
install:
    - sudo apt-get install -y build-essential debhelper devscripts equivs
    - sudo mk-build-deps --install debian/control
    - sudo apt-get install -y -f
script:
    - debuild -S -us -uc --lintian-opts --profile ndn
    - debuild -us -uc --lintian-opts --profile ndn
    - sudo dpkg -i ../*.deb
