Document: ndn-perl-modules
Title: Debian ndn-perl-modules Manual
Author: <insert document author here>
Abstract: This manual describes what ndn-perl-modules is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ndn-perl-modules/ndn-perl-modules.sgml.gz

Format: postscript
Files: /usr/share/doc/ndn-perl-modules/ndn-perl-modules.ps.gz

Format: text
Files: /usr/share/doc/ndn-perl-modules/ndn-perl-modules.text.gz

Format: HTML
Index: /usr/share/doc/ndn-perl-modules/html/index.html
Files: /usr/share/doc/ndn-perl-modules/html/*.html
